services:
  - type: web
    name: my-accounting
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: FLASK_ENV
        value: production